name: x_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-288.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http:
  google_fonts:
  dio: 
  cookie_jar: 
  dio_cookie_manager: ^3.1.1
  flutter_session_jwt:
  flutter_secure_storage_web:
  animations:
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\images\LinkifyLogo.png
    - assets\images\placeholder.png